# Init

In [2]:
import os
import openai
from rich import print
from rich import inspect

from IPython.core.interactiveshell import InteractiveShell
InteractiveShell.ast_node_interactivity = "all"

In [3]:
openai.api_key = os.getenv("OPENAI_API_KEY")


def ai(prompt, model):
    # model = ['text','code']
    response = openai.Completion.create(
        model="{0}-davinci-002".format(model),
        prompt=prompt,
        temperature=0,
        max_tokens=300,
        top_p=1,
        frequency_penalty=0,
        presence_penalty=0,
    )

    print(response["choices"][0]["text"])

# Questions

## 1

In [4]:
prompt1 = "Download Sofi stock price from yahoo finance api over the last month and plot it"

In [5]:
ai(prompt1, 'code')

import pandas as pd
import matplotlib.pyplot as plt
import datetime
import pandas_datareader.data as web

start = datetime.datetime(2020, 1, 1)
end = datetime.datetime(2020, 2, 1)

df = web.DataReader("SOFI", 'yahoo', start, end)

df.plot()
plt.show()

In [6]:
import pandas as pd
from pandas.tseries.offsets import DateOffset
import pandas_datareader.data as web
from datetime import date
import datetime

In [7]:
end = date.today()
start= end - DateOffset(months=1) 

end
start

datetime.date(2022, 11, 12)

Timestamp('2022-10-12 00:00:00')

In [8]:

df = web.DataReader("SOFI", 'yahoo', start, end)

In [9]:
df

             High    Low   Open  Close     Volume  Adj Close
Date
2022-10-12  5.120  4.880  4.980   5.08   26339800       5.08
2022-10-13  5.220  4.840  4.890   5.09   32629000       5.09
2022-10-14  5.280  4.810  5.190   4.81   35776200       4.81
2022-10-17  5.100  4.850  4.950   5.07   33347900       5.07
2022-10-18  5.350  5.150  5.250   5.25   37401900       5.25
2022-10-19  5.220  4.970  5.210   4.99   35412300       4.99
2022-10-20  5.190  4.960  4.975   5.01   30718900       5.01
2022-10-21  5.160  4.900  4.970   5.15   33980000       5.15
2022-10-24  5.200  4.970  5.140   5.17   32703200       5.17
2022-10-25  5.680  5.190  5.200   5.66   49264000       5.66
2022-10-26  5.770  5.500  5.525   5.54   37510600       5.54
2022-10-27  5.660  5.344  5.620   5.35   26942700       5.35
2022-10-28  5.470  5.290  5.370   5.45   28751000       5.45
2022-10-31  5.670  5.360  5.560   5.44   61549200       5.44
2022-11-01  6.470  5.670  6.460   5.73  159097200       5.73
2022-11-02  5.700  5.030  5.675   5.12  106803800       5.12
2022-11-03  5.390  5.010  5.030   5.36   55484100       5.36
2022-11-04  5.510  5.060  5.495   5.18   53427700       5.18
2022-11-07  5.285  5.120  5.230   5.18   39915100       5.18
2022-11-08  5.300  5.050  5.180   5.10   48009700       5.10
2022-11-09  5.060  4.940  5.030   4.98   45924000       4.98
2022-11-10  5.440  5.090  5.270   5.34   69817600       5.34
2022-11-11  6.000  5.320  5.320   5.95   84180400       5.95

In [10]:
ai("Use Adj Close from df calculate daily returns",'code')

daily_returns = df['Adj Close'].pct_change()

#Replace NA values with 0
daily_returns.fillna(0, inplace=True)

#print daily_returns

#Daily returns histogram
daily_returns.hist(bins=20)

#Get mean and standard deviation
mean = daily_returns['AAPL'].mean()
std = daily_returns['AAPL'].std()

#print mean
#print std

#Plot a line for mean and one for +1 std and -1 std
plt.axvline(mean, color='w', linestyle='dashed', linewidth=2)
plt.axvline(std, color='r', linestyle='dashed', linewidth=2)
plt.axvline(-std, color='r', linestyle='dashed', linewidth=2)

#Show plot
plt.show()

#Compute kurtosis
print daily_returns.kurtosis()

In [11]:
df['daily_returns'] = df['Adj Close'].pct_change()
df
print(f'{df.daily_returns.mean():%}, Average returns for $SOFI in the last month was less than 1% ')

             High    Low   Open  Close     Volume  Adj Close  daily_returns
Date
2022-10-12  5.120  4.880  4.980   5.08   26339800       5.08            NaN
2022-10-13  5.220  4.840  4.890   5.09   32629000       5.09       0.001969
2022-10-14  5.280  4.810  5.190   4.81   35776200       4.81      -0.055010
2022-10-17  5.100  4.850  4.950   5.07   33347900       5.07       0.054054
2022-10-18  5.350  5.150  5.250   5.25   37401900       5.25       0.035503
2022-10-19  5.220  4.970  5.210   4.99   35412300       4.99      -0.049524
2022-10-20  5.190  4.960  4.975   5.01   30718900       5.01       0.004008
2022-10-21  5.160  4.900  4.970   5.15   33980000       5.15       0.027944
2022-10-24  5.200  4.970  5.140   5.17   32703200       5.17       0.003883
2022-10-25  5.680  5.190  5.200   5.66   49264000       5.66       0.094778
2022-10-26  5.770  5.500  5.525   5.54   37510600       5.54      -0.021201
2022-10-27  5.660  5.344  5.620   5.35   26942700       5.35      -0.034296
2022-10-28  5.470  5.290  5.370   5.45   28751000       5.45       0.018692
2022-10-31  5.670  5.360  5.560   5.44   61549200       5.44      -0.001835
2022-11-01  6.470  5.670  6.460   5.73  159097200       5.73       0.053309
2022-11-02  5.700  5.030  5.675   5.12  106803800       5.12      -0.106457
2022-11-03  5.390  5.010  5.030   5.36   55484100       5.36       0.046875
2022-11-04  5.510  5.060  5.495   5.18   53427700       5.18      -0.033582
2022-11-07  5.285  5.120  5.230   5.18   39915100       5.18       0.000000
2022-11-08  5.300  5.050  5.180   5.10   48009700       5.10      -0.015444
2022-11-09  5.060  4.940  5.030   4.98   45924000       4.98      -0.023529
2022-11-10  5.440  5.090  5.270   5.34   69817600       5.34       0.072289
2022-11-11  6.000  5.320  5.320   5.95   84180400       5.95       0.114232

0.848440%, Average returns for $SOFI in the last month was less than 1%

In [36]:
# 5.25  -> 100% 
# 5.95 -> x 



p = .7/ 5.25

5.25 + (5.25 * p )

5.95

## Embed a tweet in a nb

In [1]:
# %%html
# <blockquote class="twitter-tweet"><p lang="en" dir="ltr">We&#39;ve found a new way to prompt language models that improves their ability to answer complex questions <br>Our Self-ask prompt first has the model ask and answer simpler subquestions. This structure makes it easy to integrate Google Search into an LM. Watch our demo with GPT-3 🧵⬇️ <a href="https://t.co/zYPvMBB1Ws">pic.twitter.com/zYPvMBB1Ws</a></p>&mdash; Ofir Press (@OfirPress) <a href="https://twitter.com/OfirPress/status/1577302733383925762?ref_src=twsrc%5Etfw">October 4, 2022</a></blockquote> <script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script>

## 2

In [8]:
ai("What is the average lifespan of people living in Bournemouth?", "text")#

There is no definitive answer to this question as it can vary greatly depending on a number
of factors such as lifestyle, genetics, and access to healthcare. However, according to the
Office for National Statistics, the average life expectancy for all people in the UK is
currently 79 years.